apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLW1zZmhlZ3NCSFpwNmpvU0plTkdMNURLY1dMdjY=
  NEXTAUTH_SECRET: HfwHnl1tJExrcmbhC+wRydtanAHuDoxqB7a36qdcRg8=
  NEXT_PUBLIC_API_KEY: QUl6YVN5QmJzOEZsaW9iaEhGMjZoQTFTNTgzb2p4cGxfRlAyY0pN
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4xMjM=
